/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package infraestructure.adapter.in.swing;

import application.port.in.ContratarProfesorUseCase;
import application.port.in.command.ContratarProfesorCommand;
import domain.model.profesor.Profesor;
import domain.port.out.repositories.RepositorioDeProfesores;
import domain.valueobjects.profesor.ProfesorId;
import jakarta.annotation.PostConstruct;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author lm-carlos
 */
@Component
public class JFrameCrearContrato extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameCrearContrato.class.getName());
    private List<ProfesorItem> todosLosProfesores;

    /**
     * Creates new form JFrameCrearContrato
     */
    public JFrameCrearContrato() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        todosLosProfesores = new ArrayList<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
    }

    @PostConstruct
    private void init() {
        cargarProfesores();
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {
        // Actualizar la lista de profesores cada vez que se muestra el formulario
        cargarProfesores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numeroContrato = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        salarioContrato = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fechaInicioContrato = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fechaFinContrato = new com.toedter.calendar.JDateChooser();
        profesorContrato = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        filtroProfesor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cicloAcademicoContrato = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Crear Contrato");

        jButton2.setText("Limpiar Formulario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionLimpiarFormulario(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Profesor");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Numero de Contrato");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Fecha de Inicio");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Fecha de Finalizacion");

        jButton1.setText("Crear Contrato");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionCrearContrato(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Salario");

        profesorContrato.setModel(new javax.swing.DefaultComboBoxModel<ProfesorItem>());

        jLabel7.setText("Filtrar profesores:");

        filtroProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AccionFiltrarProfesores(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Ciclo Académico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroContrato)
                            .addComponent(salarioContrato)
                            .addComponent(profesorContrato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaInicioContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaFinContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(filtroProfesor))
                            .addComponent(cicloAcademicoContrato))))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(profesorContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(filtroProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cicloAcademicoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(fechaInicioContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaFinContrato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(salarioContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccionLimpiarFormulario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionLimpiarFormulario
        // TODO add your handling code here:
        limpiarFormulario();

    }//GEN-LAST:event_AccionLimpiarFormulario

    private void AccionCrearContrato(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionCrearContrato
        // TODO add your handling code here:
        crearContrato();
    }//GEN-LAST:event_AccionCrearContrato

    private void AccionFiltrarProfesores(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AccionFiltrarProfesores
        // TODO add your handling code here:
        filtrarProfesores();
    }//GEN-LAST:event_AccionFiltrarProfesores

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameCrearContrato().setVisible(true));
    }

    @Autowired
    private RepositorioDeProfesores repositorioDeProfesores;

    private void cargarProfesores() {
        try {
            // Obtener todos los profesores de la base de datos
            List<Profesor> profesores = repositorioDeProfesores.listar();

            // Limpiar las listas
            profesorContrato.removeAllItems();
            todosLosProfesores.clear();

            // Agregar un item vacío opcional
            profesorContrato.addItem(new ProfesorItem("", "-- Seleccionar profesor --"));

            // Llenar el combo box con los profesores
            for (Profesor profesor : profesores) {
                String nombreCompleto = profesor.getDatosPersonales().getNombres() + " "
                        + profesor.getDatosPersonales().getApellidos();
                ProfesorItem item = new ProfesorItem(
                        profesor.getId().getValue(),
                        nombreCompleto + " - " + profesor.getEspecialidad()
                );
                profesorContrato.addItem(item);
                todosLosProfesores.add(item);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar profesores: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarFormulario() {
        profesorContrato.setSelectedIndex(0);
        filtroProfesor.setText("");
        numeroContrato.setText("");
        cicloAcademicoContrato.setText("");
        fechaInicioContrato.setDate(null);
        fechaFinContrato.setDate(null);
        salarioContrato.setText("");
    }

    @Autowired
    private ContratarProfesorUseCase contratarProfesorUseCase;

    private void crearContrato() {
        try {
            // Validar campos obligatorios
            if (profesorContrato.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Debe seleccionar un profesor",
                        "Error de validación",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (numeroContrato.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "El número de contrato es obligatorio",
                        "Error de validación",
                        JOptionPane.ERROR_MESSAGE);
                numeroContrato.requestFocus();
                return;
            }

            if (cicloAcademicoContrato.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "El ciclo académico es obligatorio",
                        "Error de validación",
                        JOptionPane.ERROR_MESSAGE);
                cicloAcademicoContrato.requestFocus();
                return;
            }

            if (fechaInicioContrato.getDate() == null) {
                JOptionPane.showMessageDialog(this,
                        "La fecha de inicio es obligatoria",
                        "Error de validación",
                        JOptionPane.ERROR_MESSAGE);
                fechaInicioContrato.requestFocus();
                return;
            }

            if (fechaFinContrato.getDate() == null) {
                JOptionPane.showMessageDialog(this,
                        "La fecha de fin es obligatoria",
                        "Error de validación",
                        JOptionPane.ERROR_MESSAGE);
                fechaFinContrato.requestFocus();
                return;
            }

            if (salarioContrato.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "El salario es obligatorio",
                        "Error de validación",
                        JOptionPane.ERROR_MESSAGE);
                salarioContrato.requestFocus();
                return;
            }

            // Obtener los valores del formulario
            ProfesorItem profesorSeleccionado = (ProfesorItem) profesorContrato.getSelectedItem();
            String numero = numeroContrato.getText().trim();
            String cicloAcademico = cicloAcademicoContrato.getText().trim();

            // Convertir Date a LocalDate
            LocalDate fechaInicio = fechaInicioContrato.getDate().toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();
            LocalDate fechaFin = fechaFinContrato.getDate().toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();

            double salario;
            try {
                salario = Double.parseDouble(salarioContrato.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "El salario debe ser un número válido",
                        "Error de validación",
                        JOptionPane.ERROR_MESSAGE);
                salarioContrato.requestFocus();
                return;
            }

            // Crear el comando
            ProfesorId profesorId = new ProfesorId(profesorSeleccionado.getId());
            ContratarProfesorCommand command = new ContratarProfesorCommand(
                    profesorId,
                    numero,
                    cicloAcademico,
                    fechaInicio,
                    fechaFin,
                    salario
            );

            // Ejecutar el caso de uso
            contratarProfesorUseCase.handle(command);

            JOptionPane.showMessageDialog(this,
                    "Contrato creado exitosamente",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

            // Limpiar el formulario después de crear
            limpiarFormulario();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al crear contrato: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error al crear contrato", e);
        }
    }

    private void filtrarProfesores() {
        String filtro = filtroProfesor.getText().toLowerCase().trim();

        // Limpiar el combo box
        profesorContrato.removeAllItems();
        profesorContrato.addItem(new ProfesorItem("", "-- Seleccionar profesor --"));

        // Si no hay profesores cargados, cargarlos primero
        if (todosLosProfesores.isEmpty()) {
            cargarProfesores();
            return;
        }

        // Filtrar de la lista cacheada
        for (ProfesorItem profesor : todosLosProfesores) {
            String textoProfesor = profesor.toString().toLowerCase();

            // Buscar en el texto completo (nombre + apellido + especialidad)
            if (filtro.isEmpty() || textoProfesor.contains(filtro)) {
                profesorContrato.addItem(profesor);
            }
        }

        // ELIMINA esta línea para evitar ciclo infinito:
        // filtroProfesor.setText(filtro);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cicloAcademicoContrato;
    private com.toedter.calendar.JDateChooser fechaFinContrato;
    private com.toedter.calendar.JDateChooser fechaInicioContrato;
    private javax.swing.JTextField filtroProfesor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField numeroContrato;
    private javax.swing.JComboBox<ProfesorItem> profesorContrato;
    private javax.swing.JTextField salarioContrato;
    // End of variables declaration//GEN-END:variables
}
