/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package infraestructure.adapter.in.swing;

import domain.model.profesor.Contrato;
import domain.model.profesor.Profesor;
import domain.port.out.repositories.RepositorioDeContratos;
import domain.port.out.repositories.RepositorioDeProfesores;
import jakarta.annotation.PostConstruct;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author lm-carlos
 */
@Component
public class JFrameListaContratos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameListaContratos.class.getName());
    private List<ProfesorItem> todosLosProfesores;

    /**
     * Creates new form JFrameListaContratos
     */
    public JFrameListaContratos() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        todosLosProfesores = new ArrayList<>();

        // Configurar la tabla con las columnas correctas
        configurarTabla();

        // Agregar listener al combobox
        selectorProfesor.addActionListener(e -> filtrarContratosPorProfesor());

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
    }

    @PostConstruct
    private void init() {
        cargarProfesores();
        cargarContratos();
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {
        // Actualizar la lista de profesores cada vez que se muestra el formulario
        cargarProfesores();
        cargarContratos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContratos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        selectorProfesor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Lista de Contratos");

        tablaContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaContratos);

        jLabel1.setText("Profesor:");

        selectorProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(selectorProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(selectorProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameListaContratos().setVisible(true));
    }

    @Autowired
    private RepositorioDeProfesores repositorioDeProfesores;

    @Autowired
    private RepositorioDeContratos repositorioDeContratos;

    private void configurarTabla() {
        // Definir las columnas de la tabla
        String[] columnNames = {"ID", "Número", "Profesor", "Ciclo Académico", "Fecha Inicio", "Fecha Fin", "Salario"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer la tabla no editable
            }
        };
        tablaContratos.setModel(model);
    }

    private void cargarProfesores() {
        try {
            List<Profesor> profesores = repositorioDeProfesores.listar();

            selectorProfesor.removeAllItems();
            todosLosProfesores.clear();

            // Agregar opción "Todos los profesores"
            selectorProfesor.addItem("-- Todos los profesores --");

            for (Profesor profesor : profesores) {
                String nombreCompleto = profesor.getDatosPersonales().getNombres() + " "
                        + profesor.getDatosPersonales().getApellidos();
                ProfesorItem item = new ProfesorItem(
                        profesor.getId().getValue(),
                        nombreCompleto + " - " + profesor.getEspecialidad()
                );
                selectorProfesor.addItem(item.toString());
                todosLosProfesores.add(item);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar profesores: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error al cargar profesores", e);
        }
    }

    private void cargarContratos() {
        try {
            List<Contrato> contratos = repositorioDeContratos.listar();
            mostrarContratosEnTabla(contratos);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar contratos: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error al cargar contratos", e);
        }
    }

    private void mostrarContratosEnTabla(List<Contrato> contratos) {
        DefaultTableModel model = (DefaultTableModel) tablaContratos.getModel();
        model.setRowCount(0); // Limpiar tabla

        for (Contrato contrato : contratos) {
            // Buscar el nombre del profesor
            String nombreProfesor = obtenerNombreProfesor(contrato.getProfesorId().getValue());

            model.addRow(new Object[]{
                contrato.getId().getValue(),
                contrato.getNumero(),
                nombreProfesor,
                contrato.getCicloAcademico(),
                contrato.getFechaInicio().toString(),
                contrato.getFechaFin().toString(),
                String.format("$%.2f", contrato.getSalario())
            });
        }
    }

    private String obtenerNombreProfesor(String profesorId) {
        for (ProfesorItem profesor : todosLosProfesores) {
            if (profesor.getId().equals(profesorId)) {
                return profesor.toString().split(" - ")[0]; // Solo el nombre sin especialidad
            }
        }
        return "Profesor no encontrado";
    }

    private void filtrarContratosPorProfesor() {
        try {
            int selectedIndex = selectorProfesor.getSelectedIndex();

            if (selectedIndex <= 0) {
                // Mostrar todos los contratos (cuando se selecciona "Todos los profesores")
                cargarContratos();
            } else {
                // Filtrar contratos por profesor seleccionado
                ProfesorItem profesorSeleccionado = todosLosProfesores.get(selectedIndex - 1);

                List<Contrato> todosLosContratos = repositorioDeContratos.listar();
                List<Contrato> contratosFiltrados = new ArrayList<>();

                for (Contrato contrato : todosLosContratos) {
                    if (contrato.getProfesorId().getValue().equals(profesorSeleccionado.getId())) {
                        contratosFiltrados.add(contrato);
                    }
                }

                mostrarContratosEnTabla(contratosFiltrados);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al filtrar contratos: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error al filtrar contratos", e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectorProfesor;
    private javax.swing.JTable tablaContratos;
    // End of variables declaration//GEN-END:variables
}
