package infraestructure.adapter.in.swing.Alumnos;

import com.github.lgooddatepicker.components.DatePicker;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import infraestructure.adapter.in.AlumnosController;
import infraestructure.adapter.in.CursoController;
import infraestructure.adapter.in.MatriculasController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.*;
import java.time.LocalDate;
import java.util.Locale;
import java.util.Optional;

@Component
public class JFrameMatricularAlumno extends JFrame {

    private JPanel matricularAlumnoPanel;
    private JTextField alumnoIdinput;
    private JTextField cursoIdinput;
    private DatePicker fechaInscripcionInput;
    private JButton guardarButton;

    private ApplicationContext context;

    @Autowired
    public JFrameMatricularAlumno(ApplicationContext context) {
        setContentPane(matricularAlumnoPanel);
        setTitle("Matricular Alumno");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(false);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                JFrameAlumnos ventanaAlumnos = context.getBean(JFrameAlumnos.class);
                ventanaAlumnos.setVisible(true);
            }
        });

        guardarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int alumnoId = Integer.parseInt(alumnoIdinput.getText());
                int cursoId = Integer.parseInt(cursoIdinput.getText());
                LocalDate fechaInscripcion = fechaInscripcionInput.getDate();

                CursoController cursoController = context.getBean(CursoController.class);
                Optional validarCurso = cursoController.buscarCursoPorId(cursoId);

                AlumnosController alumnosController = context.getBean(AlumnosController.class);
                Optional validarAlumno = alumnosController.buscarAlumnoPorId(alumnoId);

                if (validarCurso.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "El curso con ID " + cursoId + " no existe.");
                    return;
                }

                if (validarAlumno.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "El alumno con ID " + alumnoId + " no existe.");
                    return;
                }


                MatriculasController matriculasController = context.getBean(MatriculasController.class);
                matriculasController.matricularAlumno(
                        alumnoId,
                        cursoId,
                        fechaInscripcion
                );
                JOptionPane.showMessageDialog(null, "Alumno matriculado con éxito");
                limpiarPantalla();
            }
        });
    }

    public void limpiarPantalla() {
        alumnoIdinput.setText("");
        cursoIdinput.setText("");
        fechaInscripcionInput.setDate(null);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        matricularAlumnoPanel = new JPanel();
        matricularAlumnoPanel.setLayout(new GridLayoutManager(5, 2, new Insets(10, 10, 10, 10), -1, 10));
        final JLabel label1 = new JLabel();
        label1.setText("Alumno ID");
        matricularAlumnoPanel.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Curso ID");
        matricularAlumnoPanel.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Fecha Inscripcion");
        matricularAlumnoPanel.add(label3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        alumnoIdinput = new JTextField();
        matricularAlumnoPanel.add(alumnoIdinput, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cursoIdinput = new JTextField();
        matricularAlumnoPanel.add(cursoIdinput, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        fechaInscripcionInput = new DatePicker();
        matricularAlumnoPanel.add(fechaInscripcionInput, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$(null, -1, 24, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setText("Matricular Alumno");
        matricularAlumnoPanel.add(label4, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        guardarButton = new JButton();
        guardarButton.setText("Guardar");
        matricularAlumnoPanel.add(guardarButton, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return matricularAlumnoPanel;
    }

}
